In [28]:
import pandas as pd
import numpy as py

In [29]:
file = "purchase_data.json"

In [319]:
# The correct encoding must be used to read the CSV in pandas
purchase_data_df = pd.read_json(file)
purchase_data_df.head(50)  
top_spender_df = pd.read_json(file)
top_spender_df.head(5000)

,Age,Gender,Item ID,Item Name,Price,SN
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46
2,34,Male,174,Primitive Blade,2.46,Assastnya25
3,21,Male,92,Final Critic,1.36,Pheusrical25
4,23,Male,63,Stormfury Mace,1.27,Aela59
5,20,Male,10,Sleepwalker,1.73,Tanimnya91
6,20,Male,153,Mercenary Sabre,4.57,Undjaskla97
7,29,Female,169,"Interrogator, Blood Blade of the Queen",3.32,Iathenudil29
8,25,Male,118,"Ghost Reaver, Longsword of Magic",2.77,Sondenasta63
9,31,Male,99,"Expiration, Warscythe Of Lost Worlds",4.53,Hilaerin92
10,24,Male,57,"Despair, Favor of Due Diligence",3.81,Chamosia29
11,20,Male,47,"Alpha, Reach of Ending Hope",1.55,Sally64
12,30,Male,81,Dreamkiss,4.06,Iskossa88
13,23,Male,77,"Piety, Guardian of Riddles",3.68,Seorithstilis90
14,40,Male,44,Bonecarvin Battle Axe,2.46,Sundast29
15,21,Male,96,Blood-Forged Skeletal Spine,4.77,Haellysu29
16,22,Female,123,Twilight's Carver,1.14,Sundista85
17,22,Female,59,"Lightning, Etcher of the King",1.65,Aenarap34
18,28,Male,91,Celeste,3.71,Iskista88
19,31,Male,177,"Winterthorn, Defender of Shifting Worlds",4.89,Assossa43
20,24,Male,78,"Glimmer, Ender of the Moon",2.33,Irith83
21,15,Male,3,Phantomlight,1.79,Iaralrgue74
22,11,Female,11,Brimstone,2.52,Deural48
23,19,Male,183,Dragon's Greatsword,2.36,Chanosia65
24,11,Male,65,Conqueror Adamantite Mace,1.96,Qarwen67
25,21,Male,63,Stormfury Mace,1.27,Idai61
26,29,Male,132,Persuasion,3.90,Aerithllora36
27,34,Male,106,Crying Steel Sickle,2.29,Assastnya25
28,15,Male,49,"The Oculus, Token of Lost Worlds",4.23,Ilariarin45
29,16,Female,45,Glinting Glass Edge,2.46,Phaedai25
...,...,...,...,...,...,...
750,23,Male,86,Stormfury Lantern,1.28,Eollym91
751,26,Female,179,"Wolf, Promise of the Moonwalker",1.88,Lisjasksda68
752,15,Female,116,Renewed Skeletal Katana,2.37,Yalostiphos68
753,20,Male,4,Bloodlord's Fetish,2.28,Thryallym62
754,31,Male,104,Gladiator's Glaive,1.36,Sondastan54
755,22,Female,179,"Wolf, Promise of the Moonwalker",1.88,Ailaesuir66
756,22,Male,6,Rusty Skull,1.20,Siasri67
757,35,Male,11,Brimstone,2.52,Seosri62
758,20,Male,122,Unending Tyranny,1.21,Ryastycal90
759,19,Male,87,"Deluge, Edge of the West",2.20,Chanirrasta87
760,29,Male,81,Dreamkiss,4.06,Aerithllora36
761,28,Male,175,Woeful Adamantite Claymore,1.24,Raeduerin33
762,36,Male,52,Hatred,4.39,Lisosiast26
763,27,Other / Non-Disclosed,48,"Rage, Legacy of the Lone Victor",4.32,Eurisuru25
764,25,Male,70,Hope's End,3.89,Assassasda84
765,15,Male,13,Serenity,1.49,Aerithnucal56
766,22,Female,84,Arcane Gem,2.23,Nitherian58
767,20,Male,122,Unending Tyranny,1.21,Hailaphos89
768,21,Male,158,"Darkheart, Butcher of the Champion",3.56,Chamucosda93
769,24,Male,73,Ritual Mace,3.74,Frichilsasya78
770,22,Male,141,Persuasion,3.27,Aenasu69
771,24,Male,25,Hero Cane,1.03,Lassista97
772,15,Male,31,Trickster,2.07,Sidap51
773,21,Male,44,Bonecarvin Battle Axe,2.46,Chamadarsda63
774,24,Male,123,Twilight's Carver,1.14,Lassassast73
775,22,Male,98,"Deadline, Voice Of Subtlety",3.62,Eural50
776,14,Male,104,Gladiator's Glaive,1.36,Lirtossa78
777,20,Male,117,"Heartstriker, Legacy of the Light",4.15,Tillyrin30
778,20,Male,75,Brutality Ivory Warmace,1.72,Quelaton80
779,23,Female,107,"Splitter, Foe Of Subtlety",3.61,Alim85

In [258]:
print("Total Players:" + str(purchase_data_df["SN"].nunique()))

Total Players:573

In [98]:
unique_items = purchase_data_df["Item ID"].nunique()
unique_items
average_price = purchase_data_df["Price"].mean()
average_price
num_of_purchases = purchase_data_df["Item ID"].count()
num_of_purchases
tot_revenue = purchase_data_df["Price"].sum()
tot_revenue

purchase_summary=pd.DataFrame({"Number of Unique Items ":[unique_items],
                            "Average Price " : [average_price],
                            "Num of Purchases ": [num_of_purchases],
                            "Total Revenue " : [tot_revenue]})
purchase_summary

   Average Price   Num of Purchases   Number of Unique Items   Total Revenue
0        2.931192                780                      183         2286.33

In [178]:
male_df = purchase_data_df.loc[purchase_data_df["Gender"]== "Male"]
male_df

female_df = purchase_data_df.loc[purchase_data_df["Gender"]== "Female"]
female_df
other_df = purchase_data_df.loc[purchase_data_df["Gender"]== "Other / Non-Disclosed"]
other_df

male_count = len(male_df)
male_count

female_count = len(female_df)
female_count

other_count = len(other_df)
other_count

total_count = pd.to_numeric(male_count) + pd.to_numeric(female_count) + pd.to_numeric(other_count)
total_count

male_percent = round(( pd.to_numeric(male_count) / total_count ) *100, 2)
male_percent

female_percent = round(( pd.to_numeric(female_count) /total_count) * 100, 2)
female_percent

other_percent = round(( pd.to_numeric(other_count) / total_count ) * 100, 2)
other_percent

#gender_summary = pd.DataFrame(purchase_data_df["Gender"].value_counts())
#gender_summary

#male_count = gender_summary.iloc[0,0]
#male_count
#female_count = gender_summary.iloc[1,0]
#female_count
#other_count = gender_summary.iloc[2,0]
#other_count
#tot_count = pd.to_numeric(male_count) + pd.to_numeric(female_count) + pd.to_numeric(other_count)
#tot_count
#male_percent = (pd.to_numeric(male_count) / pd.to_numeric(tot_count) ) * 100
#male_percent
#female_percent = ( pd.to_numeric(female_count) / tot_count ) * 100
#female_percent
#other_percent = ( pd.to_numeric(other_count) / tot_count ) * 100
#other_percent

gender_summary_df = pd.DataFrame({"Male":[male_percent, male_count],
                                 "Female": [female_percent, female_count],
                                  "Other / Non Disclosed": [other_percent, other_count]})
gender_summary_df

   Female    Male  Other / Non Disclosed
0   17.44   81.15                   1.41
1  136.00  633.00                  11.00

In [195]:
female_purchase_average_price = round(female_df["Price"].mean(), 2)
female_purchase_average_price
female_tot_purchase_value = round(female_df["Price"].sum(),2)
female_tot_purchase_value
female_unique = female_df["SN"].nunique()
female_unique
female_normalized_tot = female_tot_purchase_value/female_unique
female_normalized_tot
female_count = len(female_df)
female_count

male_purchase_average_price = round(male_df["Price"].mean(), 2)
male_purchase_average_price
male_tot_purchase_value = round(male_df["Price"].sum(),2)
male_tot_purchase_value
male_unique = male_df["SN"].nunique()
male_unique
male_normalized_tot = male_tot_purchase_value/male_unique
male_normalized_tot
male_count = len(male_df)
male_count

other_purchase_average_price = round(other_df["Price"].mean(), 2)
other_purchase_average_price
other_tot_purchase_value = round(other_df["Price"].sum(),2)
other_tot_purchase_value
other_unique = other_df["SN"].nunique()
other_unique
other_normalized_tot = other_tot_purchase_value/other_unique
other_normalized_tot
other_count = len(other_df)
other_count 


purchasing_analysis_df = pd.DataFrame({"Female":[female_count, female_purchase_average_price, female_tot_purchase_value, female_normalized_tot ],
                                 "Male": [male_count, male_purchase_average_price, male_tot_purchase_value, male_normalized_tot ],
                                  "Other / Non Disclosed": [male_count, male_purchase_average_price, male_tot_purchase_value, male_normalized_tot ]})


purchasing_analysis_df

     Female         Male  Other / Non Disclosed
0  136.0000   633.000000             633.000000
1    2.8200     2.950000               2.950000
2  382.9100  1867.680000            1867.680000
3    3.8291     4.016516               4.016516

In [259]:
print(purchase_data_df["Age"].max())
print(purchase_data_df["Age"].min())

45
7

In [197]:
bins = [0,9,14,19,24,29,34, 39, 100]
group_name = ['<10','10-14', '15-19', '20-24', '25-29', '20-34', '35-39', '40+' ]

In [199]:
# Slice the age data and place it into bins
pd.cut(purchase_data_df["Age"],bins,labels=group_name).head(20)

0     35-39
1     20-24
2     20-34
3     20-24
4     20-24
5     20-24
6     20-24
7     25-29
8     25-29
9     20-34
10    20-24
11    20-24
12    20-34
13    20-24
14      40+
15    20-24
16    20-24
17    20-24
18    25-29
19    20-34
Name: Age, dtype: category
Categories (8, object): [<10 < 10-14 < 15-19 < 20-24 < 25-29 < 20-34 < 35-39 < 40+]

In [201]:
# Place the data series into a new column inside of the DataFrame
purchase_data_df["Age Group"] = pd.cut(purchase_data_df["Age"],bins,labels=group_name)
purchase_data_df.head(10)

,Age,Gender,Item ID,Item Name,Price,SN,Age Group
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34,35-39
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46,20-24
2,34,Male,174,Primitive Blade,2.46,Assastnya25,20-34
3,21,Male,92,Final Critic,1.36,Pheusrical25,20-24
4,23,Male,63,Stormfury Mace,1.27,Aela59,20-24
5,20,Male,10,Sleepwalker,1.73,Tanimnya91,20-24
6,20,Male,153,Mercenary Sabre,4.57,Undjaskla97,20-24
7,29,Female,169,"Interrogator, Blood Blade of the Queen",3.32,Iathenudil29,25-29
8,25,Male,118,"Ghost Reaver, Longsword of Magic",2.77,Sondenasta63,25-29
9,31,Male,99,"Expiration, Warscythe Of Lost Worlds",4.53,Hilaerin92,20-34

In [276]:
# Create a GroupBy object based upon "Age Group"
tot = len(purchase_data_df)
#print(tot)
purchase_group = purchase_data_df.groupby("Age Group")
#purchase_group.head()
 
                                                                                                                           
purchase_summary = pd.DataFrame( {"Total Count" :purchase_group["Age"].count(),
                                  "Percentage of Players" : round( purchase_group["Age"].count() *100 / tot ,2) })

purchase_summary

           Percentage of Players  Total Count
Age Group
<10                         3.59           28
10-14                       4.49           35
15-19                      17.05          133
20-24                      43.08          336
25-29                      16.03          125
20-34                       8.21           64
35-39                       5.38           42
40+                         2.18           17

In [288]:
purchase_count = purchase_group["Item ID"].sum()
purchase_count
average_purchase_price = round(purchase_group["Price"].mean(),2)
average_purchase_price
total_purchase_value = round(purchase_group["Price"].sum())
total_purchase_value
normalized_total = purchase_group["SN"].nunique()
normalized_total

Age Group
<10       19
10-14     23
15-19    100
20-24    259
25-29     87
20-34     47
35-39     27
40+       11
Name: SN, dtype: int64

In [324]:
purchasing_analysis_summary = pd.DataFrame({"Purchase Count":purchase_count,
                                            "Average Purchase Price":average_purchase_price,
                                            "Total Purchase Value": total_purchase_value,
                                           "Normalized Totals":normalized_total })
purchasing_analysis_summary

,Average Purchase Price,Normalized Totals,Purchase Count,Total Purchase Value
Age Group,,,,
<10,2.98,19,2305,83.0
10-14,2.77,23,3171,97.0
15-19,2.91,100,12561,386.0
20-24,2.91,259,28909,979.0
25-29,2.96,87,11729,370.0
20-34,3.08,47,6493,197.0
35-39,2.84,27,4497,119.0
40+,3.16,11,1544,54.0

In [323]:
#Just for testing
my_df = top_spender_df.loc[top_spender_df["SN"]== "Aelalis34"]
my_df

     Age Gender  Item ID                    Item Name  Price         SN
0     38   Male      165  Bone Crushing Silver Skewer   3.37  Aelalis34
529   38   Male      172           Blade of the Grave   1.69  Aelalis34

In [321]:
top_spenders_group = top_spender_df.groupby("SN")
top_spenders_group.head()

ts_count = top_spenders_group["Item ID"].count()
ts_count

ts_average_purchase_price = round(top_spenders_group["Price"].mean(), 2)
ts_average_purchase_price

ts_tot_purchase_value = round(top_spenders_group["Price"].sum(), 2)
ts_tot_purchase_value

top_spender_summary = pd.DataFrame( {"Purchase Count":ts_count,
                                     "Average Purchase Price":ts_average_purchase_price,
                                     "Total Purchase Value": ts_tot_purchase_value} )
top_spender_summary

                 Average Purchase Price  Purchase Count  Total Purchase Value
SN
Adairialis76                       2.46               1                  2.46
Aduephos78                         2.23               3                  6.70
Aeduera68                          1.93               3                  5.80
Aela49                             2.46               1                  2.46
Aela59                             1.27               1                  1.27
Aelalis34                          2.53               2                  5.06
Aelin32                            3.14               1                  3.14
Aeliriam77                         3.36               2                  6.72
Aeliriarin93                       2.04               1                  2.04
Aeliru63                           4.49               2                  8.98
Aellyria80                         4.32               1                  4.32
Aellyrialis39                      3.15               1                  3.15
Aellysup38                         3.61               1                  3.61
Aelollo59                          1.55               1                  1.55
Aenarap34                          1.65               1                  1.65
Aenasu69                           3.27               1                  3.27
Aeral43                            2.72               1                  2.72
Aeral85                            4.25               1                  4.25
Aeral97                            2.35               1                  2.35
Aeri84                             3.30               2                  6.60
Aerillorin70                       1.88               1                  1.88
Aerithllora36                      3.48               3                 10.45
Aerithnucal56                      1.59               2                  3.18
Aerithnuphos61                     1.69               1                  1.69
Aerithriaphos45                    2.38               1                  2.38
Aesty51                            1.82               1                  1.82
Aesur96                            4.66               1                  4.66
Aethe80                            2.32               1                  2.32
Aethedru70                         2.97               1                  2.97
Aidain51                           3.42               2                  6.84
...                                 ...             ...                   ...
Undjaskla97                        4.57               1                  4.57
Undjasksya56                       4.53               1                  4.53
Undotesta33                        3.90               1                  3.90
Wailin72                           2.04               1                  2.04
Whaestysu86                        4.08               1                  4.08
Yadacal26                          1.93               1                  1.93
Yadaisuir65                        4.28               2                  8.56
Yadanun74                          3.03               3                  9.09
Yalaeria91                         1.88               1                  1.88
Yaliru88                           3.71               1                  3.71
Yalo71                             2.41               1                  2.41
Yalostiphos68                      2.37               1                  2.37
Yaralnura48                        2.10               2                  4.19
Yararmol43                         1.55               1                  1.55
Yarirarn35                         2.88               1                  2.88
Yaristi64                          1.24               1                  1.24
Yarithllodeu72                     2.19               1                  2.19
Yarithphos28                       2.35               1                  2.35
Yarithsurgue62                     2.41               2                  4.81
Yarmol79                           2.91               1                  2.91
Yarolwen77                         3.49               2                  6.98
Yasriphos60                        3.47               3                 10.40
Yasrisu92                          2.60               1                  2.60
Yasur35                            2.78               1                  2.78
Yasur85                            2.04               1                  2.04
Yasurra52                          3.14               1                  3.14
Yathecal72                         3.88               2                  7.77
Yathecal82                         2.41               1                  2.41
Zhisrisu83                         1.23               2                  2.46
Zontibe81                          3.71               1                  3.71

[573 rows x 3 columns]

In [328]:
my_df = top_spender_df.loc[top_spender_df["Item ID"]== 8]
my_df

     Age  Gender  Item ID                 Item Name  Price            SN
245   30    Male        8  Purgatory, Gem of Regret   3.91  Lisistasya93
265   24    Male        8  Purgatory, Gem of Regret   3.91    Saellyra72
443   25    Male        8  Purgatory, Gem of Regret   3.91     Undadar97
543   15    Male        8  Purgatory, Gem of Regret   3.91    Seolollo93
652   21  Female        8  Purgatory, Gem of Regret   3.91    Styaduen40
733   16    Male        8  Purgatory, Gem of Regret   3.91  Bartassaya73

In [358]:
most_popular_group = top_spender_df.groupby("Item ID")
most_popular_group.head()

mp_count = most_popular_group["Item ID"].count()
mp_count

mp_price = most_popular_group["Price"].max()
mp_price

mp_tot_purch_value = most_popular_group["Price"].sum()
mp_tot_purch_value

most_popular_summary = pd.DataFrame( { "Purchase Count" : mp_count,
                                       "Item Name" : most_popular_group["Item Name"].max(),
                                       "Item Price": mp_price, 
                                       "Total Purchase Value": mp_tot_purch_value } )

#sort by Purchase Count
sorted_byPurchCnt_df = most_popular_summary.sort_values(by="Purchase Count", ascending = False)
sorted_byPurchCnt_df

#sort by Total Purchase Value
most_profit_item = most_popular_summary.sort_values(by="Total Purchase Value", ascending = False)
most_profit_item

#sort by Total Purchase Value AND Purchase Count
#sort_by_pv_pc = most_popular_summary.sort_values(by=["Total Purchase Value","Purchase Count"], ascending = [False, False])
#sort_by_pv_pc

,Item Name,Item Price,Purchase Count,Total Purchase Value
Item ID,,,,
34,Retribution Axe,4.14,9,37.26
115,Spectral Diamond Doomblade,4.25,7,29.75
32,Orenmir,4.95,6,29.70
103,Singed Scalpel,4.87,6,29.22
107,"Splitter, Foe Of Subtlety",3.61,8,28.88
101,Final Critic,4.62,6,27.72
7,"Thorn, Satchel of Dark Souls",4.51,6,27.06
145,Fiery Glass Crusader,4.45,6,26.70
39,"Betrayal, Whisper of Grieving Widows",2.35,11,25.85
152,Darkheart,3.15,8,25.20
102,Avenger,4.16,6,24.96
158,"Darkheart, Butcher of the Champion",3.56,7,24.92
66,Victor Iron Spikes,3.55,7,24.85
84,Arcane Gem,2.23,11,24.53
173,Stormfury Longsword,4.83,5,24.15
128,"Blazeguard, Reach of Eternity",4.00,6,24.00
148,"Warmonger, Gift of Suffering's End",3.96,6,23.76
46,Hopeless Ebon Dualblade,4.75,5,23.75
108,"Extraction, Quickblade Of Trembling Hands",3.39,7,23.73
8,"Purgatory, Gem of Regret",3.91,6,23.46
153,Mercenary Sabre,4.57,5,22.85
73,Ritual Mace,3.74,6,22.44
91,Celeste,3.71,6,22.26
48,"Rage, Legacy of the Lone Victor",4.32,5,21.60
12,Dawne,4.30,5,21.50
22,Amnesia,3.57,6,21.42
49,"The Oculus, Token of Lost Worlds",4.23,5,21.15
30,Stormcaller,4.15,5,20.75
121,Massacre,3.42,6,20.52
81,Dreamkiss,4.06,5,20.30
...,...,...,...,...
149,"Tranquility, Razor of Black Magic",2.47,2,4.94
24,Warped Fetish,2.41,2,4.82
178,"Oathbreaker, Last Hope of the Breaking Storm",2.41,2,4.82
167,"Malice, Legacy of the Queen",2.38,2,4.76
116,Renewed Skeletal Katana,2.37,2,4.74
82,Nirvana,1.11,4,4.44
25,Hero Cane,1.03,4,4.12
9,"Thorn, Conqueror of the Corrupted",2.04,2,4.08
5,Putrid Fan,1.32,3,3.96
122,Unending Tyranny,1.21,3,3.63
6,Rusty Skull,1.20,3,3.60
147,"Hellreaver, Heirloom of Inception",3.59,1,3.59
41,Orbit,1.16,3,3.48
2,Verdict,3.40,1,3.40
136,Ghastly Adamantite Protector,3.30,1,3.30
126,Exiled Mithril Longsword,3.25,1,3.25
109,"Downfall, Scalpel Of The Emperor",3.20,1,3.20
69,"Frenzy, Defender of the Harvest",1.06,3,3.18
28,"Flux, Destroyer of Due Diligence",3.04,1,3.04
89,"Blazefury, Protector of Delusions",1.50,2,3.00
72,Winter's Bite,1.39,2,2.78
168,"Sun Strike, Jaws of Twisted Visions",2.64,1,2.64
43,Foul Edge,2.38,1,2.38
4,Bloodlord's Fetish,2.28,1,2.28
74,Yearning Crusher,1.06,2,2.12
164,Exiled Doomblade,1.92,1,1.92
0,Splinter,1.82,1,1.82
3,Phantomlight,1.79,1,1.79
59,"Lightning, Etcher of the King",1.65,1,1.65
156,Soul-Forged Steel Shortsword,1.16,1,1.16